before_script:
  - sudo apt-get -y -qq install libgc-dev 
  - sudo apt-get -y -qq install libgles2-mesa-dev
  - sudo apt-get -y -qq install wget
  - export PATH=$PATH:$PWD/tools/rock/bin:$PWD/tools/sam
  - mkdir tools
  - cd tools && git clone https://github.com/zhaihj/rock
  - cd rock && make rescue
  - make clean self
  - cd ../..
  - export OOC_LIBS=$PWD/..
  - # otherwise, PWD/sdk.use will be used instead of PWD/tools/rock/sdk.use and rock will fail to compile.
  - # rock will look for .use files not in OOC_LIBS, but in subfolders to OOC_LIBS - in this case, OOC_LIBS/rock.
  - (cd tools && git clone --depth=1 git://github.com/cogneco/sam.git)
  - (cd tools/sam && rock -v)

script:
  - # because now we want to use ooc-kean/sdk.use, i.e. PWD/sdk.use.
  - cd test 
  - rock -r --gc=off -lpthread -O2 base/ProfilingTest.ooc
  - cd ..
  - sam test
